# Generated by Django 4.1 on 2023-03-27 01:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplaces", "0016_remove_solutioncard_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "type",
                    models.CharField(max_length=255, verbose_name="Тип лаборатории"),
                ),
                (
                    "header_image",
                    models.ImageField(
                        upload_to="laboratories_images",
                        verbose_name="Фото в верхней части страницы 16x9",
                    ),
                ),
                ("description", ckeditor.fields.RichTextField(verbose_name="Описание")),
                ("solutions", models.TextField(verbose_name="Решения")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "team_description",
                    models.CharField(max_length=255, verbose_name="Описание команды"),
                ),
                (
                    "team_director_bio",
                    models.CharField(max_length=255, verbose_name="ФИО руководителя"),
                ),
                (
                    "team_director_position",
                    models.CharField(
                        max_length=100, verbose_name="Должность руководителя"
                    ),
                ),
                (
                    "team_director_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="laboratories_directors_images",
                        verbose_name="Фото руководителя",
                    ),
                ),
                (
                    "team_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="laboratory_team_images",
                        verbose_name="Фото команды",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="laboratories_logo_images",
                        verbose_name="Логотип лаборатории",
                    ),
                ),
                (
                    "contact_bio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ФИО контактного лица",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Контактный email",
                    ),
                ),
                (
                    "contact_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="Контактный номер телефона",
                    ),
                ),
                (
                    "contact_other",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Другое"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
            },
        ),
        migrations.CreateModel(
            name="SocialNetResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("url", models.URLField(max_length=512, verbose_name="Ссылка")),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_nets",
                        to="laboratories.laboratory",
                        verbose_name="Лаборатория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.CreateModel(
            name="LaboratorySolutionCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution_cards",
                        to="laboratories.laboratory",
                        verbose_name="Лаборатория",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratories",
                        to="marketplaces.solutioncard",
                        verbose_name="Карточка решений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка решений",
                "verbose_name_plural": "Карточки решений",
            },
        ),
        migrations.CreateModel(
            name="LaboratoryEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.CharField(max_length=255, verbose_name="ФИО сотрудника"),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=100, verbose_name="Должность сотрудника"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="laboratories_employees_images",
                        verbose_name="Фото сотрудника",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="laboratories.laboratory",
                        verbose_name="Лаборатория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
