# Generated by Django 4.1 on 2023-03-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0016_remove_solutioncard_date"),
        ("laboratories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laboratorysolutioncards",
            options={
                "verbose_name": "Карточка разработки",
                "verbose_name_plural": "Карточки разработок",
            },
        ),
        migrations.AlterField(
            model_name="laboratorysolutioncards",
            name="solution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratories",
                to="marketplaces.solutioncard",
                verbose_name="Карточка разработки",
            ),
        ),
    ]
