services:
  postgres:
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - django_core/django_core/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps

  backend:
    restart: always
    container_name: aim_django_core
    build: ./django_core
    command: bash -c "
      python manage.py migrate &&
      gunicorn -w 3 django_core.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./django_core:/django_core
    expose:
      - 8000
    depends_on:
      - postgres

  redis:
      image: redis:7.0.4
      restart: always
      expose:
          - 6379
      volumes:
          - ./dbs/redis-data:/data/

  celery:
      build: ./django_core
      restart: always
      volumes:
          - ./django_core:/django_core
      env_file:
        - django_core/django_core/.env
      depends_on:
          - redis
      command: celery -A django_core worker -l DEBUG -c 3

  flower:
      image: mher/flower
      restart: always
      command: celery flower --persistent=True
      ports:
          - "5555:5555"
      env_file:
        - django_core/django_core/.env
      depends_on:
          - celery
      volumes:
          - ./django_core:/django_core

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./django_core/media:/app/media
