# Generated by Django 4.1 on 2022-10-11 14:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_is_deleted'),
        ('marketplaces', '0003_alter_formtemplate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Черновик?')),
                ('published_at', models.DateTimeField(blank=True, help_text='Устанавливается автоматически при сохранении новости, которая не является черновиком', null=True, verbose_name='Дата публикации')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='news_background_images', verbose_name='Фоновое изображение')),
                ('background_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет фона')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('solution_type', models.CharField(choices=[('FUL', 'Full size'), ('TWO', 'Two-sided')], default='FUL', max_length=3, verbose_name='Тип решения')),
                ('license', models.CharField(choices=[('OPE', 'Open source'), ('NON', 'Non-public license')], default='NON', max_length=3, verbose_name='Тип лицензии')),
                ('tags', models.ManyToManyField(to='news.newstag', verbose_name='Тематика')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['-published_at'],
            },
        ),
    ]
