# Generated by Django 4.1 on 2022-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('marketplaces', '0005_alter_solution_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='Тематика'),
        ),
    ]
