# Generated by Django 4.1 on 2022-10-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_alter_solution_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Устанавливается автоматически при сохранении новости, которая не является черновиком', null=True, verbose_name='Дата публикации'),
        ),
    ]
