# Generated by Django 4.1 on 2022-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0009_alter_solution_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='license',
            field=models.CharField(choices=[('Open source', 'Open source'), ('Non-public license', 'Non-public license')], default='Non-public license', max_length=32, verbose_name='Тип лицензии'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('Full size', 'Full size'), ('Two-sided', 'Two-sided')], default='Full size', max_length=32, verbose_name='Тип решения'),
        ),
    ]
