# Generated by Django 4.1 on 2022-11-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0012_mainpageheader"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainPageHeader",
        ),
    ]
