# Generated by Django 4.1 on 2022-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0014_solutioncard_date_solutioncard_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solutioncard",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="solutioncard",
            name="solution",
        ),
        migrations.AddField(
            model_name="solutioncard",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="solutioncard",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solution_card_background_images",
                verbose_name="Обложка (785x478)",
            ),
        ),
    ]
