# Generated by Django 4.1 on 2023-01-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0016_remove_solutioncard_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutioncard",
            name="solution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplaces.solution",
                verbose_name="Решение",
            ),
        ),
    ]
