# Generated by Django 4.1 on 2023-04-06 11:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0018_remove_solutioncard_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Описание"),
        ),
    ]
