# Generated by Django 4.1 on 2022-10-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0019_delete_registrationform"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                ("number", models.CharField(max_length=255, verbose_name="Телефон")),
                ("email", models.CharField(max_length=255, verbose_name="Почта")),
                (
                    "work_or_study_place",
                    models.CharField(max_length=255, verbose_name="Место работы/учёбы"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_form",
                        to="news.news",
                        verbose_name="Название мероприятия",
                    ),
                ),
            ],
        ),
    ]
