# Generated by Django 4.1 on 2022-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration_on_event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationform",
            options={
                "verbose_name": "Регистрация на мероприятие",
                "verbose_name_plural": "Регистрации на мероприятие",
            },
        ),
        migrations.AlterField(
            model_name="registrationform",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Почта"),
        ),
    ]
