# Generated by Django 4.1 on 2022-11-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0025_alter_news_title"),
        ("registration_on_event", "0002_alter_registrationform_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationform",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_form",
                to="news.news",
                verbose_name="Новость",
            ),
        ),
    ]
