# Generated by Django 4.1 on 2022-10-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tags.tag',),
        ),
    ]
