# Generated by Django 4.1 on 2022-11-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_person_unit_delete_newstype_newstype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Технология",
                "verbose_name_plural": "Технологии",
            },
        ),
    ]
