# Generated by Django 4.1 on 2022-08-28 16:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тематика новостей",
                "verbose_name_plural": "Тематики новостей",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="description",
            field=tinymce.models.HTMLField(default="", verbose_name="Общая информация"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="short_description",
            field=models.TextField(default="", verbose_name="Краткое описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="source",
            field=models.CharField(
                default="Редакция сайта",
                max_length=127,
                verbose_name="Источник новости",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="news_videos", verbose_name="Видео"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="video_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Подпись к видео"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                to="news.newscategory", verbose_name="Тематика"
            ),
        ),
    ]
