# Generated by Django 4.1 on 2022-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_newscategory_news_description_news_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="Черновик?"),
        ),
        migrations.AlterField(
            model_name="news",
            name="short_description",
            field=models.TextField(verbose_name="Краткая информация"),
        ),
    ]
