# Generated by Django 4.1 on 2022-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_is_draft_alter_news_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="show_in_feed",
            field=models.BooleanField(
                default=True,
                help_text="Влияет только на опубликованные новости",
                verbose_name="Отображать в ленте новостей",
            ),
        ),
    ]
