# Generated by Django 4.1 on 2022-08-29 08:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_news_background_color_news_background_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Раздел новостей",
                "verbose_name_plural": "Разделы новостей",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
                verbose_name="Цвет фона",
            ),
        ),
        migrations.CreateModel(
            name="NewsPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="news.news",
                        verbose_name="Новость",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.newssection",
                        verbose_name="Раздел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размещение новости",
                "verbose_name_plural": "Размещения новостей",
            },
        ),
    ]
