# Generated by Django 4.1 on 2022-08-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_newssection_alter_news_background_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="news_images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.news",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение новости",
                "verbose_name_plural": "Изображения новостей",
            },
        ),
    ]
