# Generated by Django 4.1 on 2022-08-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_newsimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsCategory",
            new_name="NewsTag",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="categories",
            new_name="tags",
        ),
    ]
