# Generated by Django 4.1 on 2022-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_news_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="video_link",
            field=models.TextField(
               blank=True, null=True, verbose_name="Ссылка на видео (YouTube)"
            )
        ),
    ]
