# Generated by Django 4.1 on 2022-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_news_add_video_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
