# Generated by Django 4.1 on 2022-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
    ]
