# Generated by Django 4.1 on 2022-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0006_alter_solution_tags'),
        ('tags', '0001_initial'),
        ('news', '0012_news_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsTag',
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='Тематика'),
        ),
    ]
