# Generated by Django 4.1 on 2022-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_delete_newstag_alter_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL', null=True),
            preserve_default=False,
        ),
    ]
