# Generated by Django 4.1 on 2022-10-12 09:47
import re

from django.db import migrations, models
from transliterate import translit


def fill_slug(apps, schema_editor):
    News = apps.get_model('news', 'News')
    news_set_title = set()
    for news in News.objects.all():
        news.slug = re.sub(
                r'[^a-zA-Z0-9-_]+',  # оставляем все [a-zA-Z0-9-_] символы
                '',
                translit(news.title, "ru", reversed=True)  # транслит заголовка
                .replace(" ", "-").lower()  # меняем пробелы на тире
            )
        if news.slug in news_set_title:
            news.slug += news.pk
        news.save(update_fields=['slug'])
        news_set_title.add(news.slug)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slug),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        )
    ]
