# Generated by Django 4.1 on 2022-10-22 19:16

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_alter_news_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                ("number", models.CharField(max_length=255, verbose_name="Телефон")),
                ("email", models.CharField(max_length=255, verbose_name="Почта")),
                (
                    "work_or_study_place",
                    models.CharField(max_length=255, verbose_name="Место учебы/работы"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_form",
                        to="news.news",
                        verbose_name="Название мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация на мероприятие",
                "verbose_name_plural": "Регистрации на мероприятие",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время начала"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата и время окончания"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место проведения",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Телефон организатора",
                    ),
                ),
                (
                    "сontact_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Почта организатора",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="registration_images",
                        verbose_name="Изображение в форме регистрации",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "consent",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="consent_on_data_processing",
                        verbose_name="файл согласия на обработку данных",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration",
                        to="news.news",
                        verbose_name="Название мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
            },
        ),
    ]
