# Generated by Django 4.1 on 2022-10-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0019_delete_registrationform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registration",
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрация",
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Название мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="news",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to="news.news",
                verbose_name="Mероприятие",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="сontact_email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Почта организатора"
            ),
        ),
    ]
