# Generated by Django 4.1 on 2022-10-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_news_news_type_news_persons_news_units'),
        ('news', '0020_alter_registration_options_registration_title_and_more'),
    ]

    operations = [
    ]
