# Generated by Django 4.1 on 2022-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_person_unit_delete_newstype_newstype"),
        ("news", "0021_merge_20221023_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_type",
            field=models.ManyToManyField(
                blank=True, null=True, to="tags.newstype", verbose_name="Рубрика"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="persons",
            field=models.ManyToManyField(
                blank=True, null=True, to="tags.person", verbose_name="Персоны"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="tags.tag", verbose_name="Тематика"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="units",
            field=models.ManyToManyField(
                blank=True, null=True, to="tags.unit", verbose_name="Подразделения"
            ),
        ),
    ]
