# Generated by Django 4.1 on 2022-11-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0023_alter_news_news_type_alter_news_persons_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="сontact_email",
            new_name="contact_email",
        ),
    ]
