# Generated by Django 4.1 on 2022-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0024_rename_сontact_email_registration_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1023, verbose_name="Заголовок новости"),
        ),
    ]
