# Generated by Django 4.1 on 2022-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_technology'),
        ('news', '0025_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.ManyToManyField(blank=True, to='tags.newstype', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='news',
            name='persons',
            field=models.ManyToManyField(blank=True, to='tags.person', verbose_name='Персоны'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='news',
            name='units',
            field=models.ManyToManyField(blank=True, to='tags.unit', verbose_name='Подразделения'),
        ),
    ]
