# Generated by Django 4.1 on 2022-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название вкладки"),
                ),
                ("url", models.URLField(verbose_name="Ссылка куда ведет кнопка")),
                (
                    "order",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вкладка информации",
                "verbose_name_plural": "Вкладки информации",
                "ordering": ["order"],
            },
        ),
    ]
